name: Build

on:
  push:
    branches: ['*']
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: curlimages/curl
    steps:
      - name: Trigger builds
        run: |
          set -e
          # systemd-debian
          curl -sXPOST https://hub.docker.com/api/build/v1/source/7ff4cb81-1669-4d8c-b71c-78d372008ca6/trigger/a713677f-000c-4d36-b10e-43ddaaba1f44/call/
          # systemd-ubuntu
          curl -sXPOST https://hub.docker.com/api/build/v1/source/e46dc792-7434-460a-a604-c2f550a4c1d9/trigger/eae24f56-bcdc-473f-a75c-05ac4b9cd399/call/
          # systemd-centos
          curl -sXPOST https://hub.docker.com/api/build/v1/source/2a412a1d-c4d0-4818-bf65-f695280494e3/trigger/d724213d-1aec-458e-9000-3075263bf6ec/call/
          # systemd-fedora
          curl -sXPOST https://hub.docker.com/api/build/v1/source/3d0619f4-95ad-4629-9995-4534e06a0076/trigger/30747760-509f-4e89-a0be-5941469a922e/call/
          # openrc-alpine
          curl -sXPOST https://hub.docker.com/api/build/v1/source/dafbfb54-1ba0-43f7-8ec5-de1fe9d1ed1a/trigger/4a4c2852-5093-47e3-b754-44eb8e9a46c5/call/
